### ISSUE TITLE
in examples as provided reporter is being used but it's not declared any variable or nor referenced.

### ISSUE THREAD

**Issue by maramrajushandilya** [zaqqaz/jest-allure#10]
const { Severity } = require("jest-allure/dist/Reporter");

const timeout = 5000;

describe(
    '/ (Home Page)',
    () => {
        let page;

        beforeAll(async () => {
            page = await global.__BROWSER__.newPage();
            await page.goto('https://google.com');
        }, timeout);

        afterAll(async () => {
            await page.close();
        });

        it('should load without error', async () => {
            reporter
                .description("Home Page test suite")
                .story("GOOGL-01")
                .severity(Severity.Critical);

            const text = await page.evaluate(() => document.body.textContent);

            reporter.startStep("Check that home page contain google");
            expect(text).toContain('google');
            reporter.endStep();

            reporter.startStep("Make a screenshot");
            const screenshot = await page.screenshot();
            reporter.addAttachment("Home Page", screenshot, "image/png");
            reporter.endStep();
        })
    },
    timeout
);

**Comment by zaqqaz** [comment]
True, readme updated.
