### ISSUE TITLE
unable to configure location of allure-reports

### ISSUE THREAD

**Issue by abendt** [zaqqaz/jest-allure#11]
Hi,

I'd like to be able to configure the directory where the allure-reports are written to. Currently this seems to be hardcoded to "allure-reports". There is an option here: https://github.com/zaqqaz/jest-allure/blob/master/src/index.ts#L13 but it doesn't seem to be used.

It would be nice to be able to configure the location via an environment variable _or_ via a configuration block within package.json.

**Comment by zaqqaz** [comment]
I'll try to look into it soon.

**Comment by abendt** [comment]
I had a look at it and came up with this: https://github.com/abendt/jest-allure/tree/CONFIGURE_ALLURE_RESULTS
* the directory can be configured using an environment variable
* added a test directory to allow testing the setup

@zaqqaz what do you think?

**Comment by tyler36** [comment]
Any updates on this?

**Comment by zaqqaz** [comment]
Should work: https://github.com/zaqqaz/jest-allure/issues/71
