### ISSUE TITLE
jest 24.1 update

### ISSUE THREAD

**Issue by gaaliche** [zaqqaz/jest-allure#13]
Hello everyone,
Since I updated to jest 24.1 I had the following error

**ReferenceError: reporter is not defined**
` 
beforeEach(async () => {`
`reporter.startStep("Log in");`
`^`
To fix this I add the following block to my jest.config.js
`  setupFilesAfterEnv: [
    '<rootDir>/jasmine.config.js'
  ]`
which contains the following code
`import { registerAllureReporter } from "jest-allure/dist/setup";`
`registerAllureReporter();`
But Now I'm having issue with the allure report, since one additional XML file is generated in allure-results.
Is it possible to remove the line _71_ in setup.ts ?
`registerAllureReporter();`

**Comment by zaqqaz** [comment]
@gaaliche, right, I'll fix readme.

Just do `import "jest-allure/dist/setup";` in your file.

**Comment by zaqqaz** [comment]
updated

**Comment by gaaliche** [comment]
Thanks for your help.
