### ISSUE TITLE
no test results

### ISSUE THREAD

**Issue by kodmis** [zaqqaz/jest-allure#14]
`C:\Users\kodmis\Documents\webprojects\fs-vue-template>npm t`
>
>> fs-vue-template@0.0.1 test C:\Users\kodmis\Documents\webprojects\fs-vue-template
>> jest --config test/jest.conf.js
>
>  PASS  test/specs/components/HelloWorld.spec.js
>   HelloWorld.vue
>     √ contains header "Welcome to Your Vue.js App" (16ms)
> 
> Test Suites: 1 passed, 1 total
> Tests:       1 passed, 1 total
> Snapshots:   0 total
> Time:        4.807s
> Ran all test suites.

`C:\Users\kodmis\Documents\webprojects\fs-vue-template>dir allure*`
>  Volume in drive C is OSDisk
>  Volume Serial Number is 38F1-E399
> 
>  Directory of C:\Users\kodmis\Documents\webprojects\fs-vue-template
> 
> File Not Found
> 
> 

`C:\Users\kodmis\projects\fs-vue-template>allure generate`
> allure-results does not exists
> Report successfully generated to allure-report
> 

`C:\Users\kodmis\Documents\webprojects\fs-vue-template>type test\jest.conf.js`
> const path = require('path');
> 
> module.exports = {
>   rootDir: path.resolve(__dirname, '../'),
>   moduleFileExtensions: ['js', 'json', 'vue'],
>   moduleNameMapper: {
>     '^@/(.*)$': '<rootDir>/src/$1',
>   },
>   transform: {
>     '^.+\\.js$': '<rootDir>/node_modules/babel-jest',
>     '.*\\.(vue)$': '<rootDir>/node_modules/vue-jest',
>   },
>   reporters: ["jest-allure", "default"],
> 
> };
>

**Comment by akaguny** [comment]
show HelloWorld.spec.js

**Comment by kevinoliveira** [comment]
i have a the same issue.

jest allure 
![image](https://user-images.githubusercontent.com/14365975/58756654-8b354200-84d3-11e9-8ea5-f2e9e6253acf.png)

jest default report 
![image](https://user-images.githubusercontent.com/14365975/58756664-cd5e8380-84d3-11e9-8512-5ca183f8e08c.png)

Versions:
- "jest": "^24.8.0",
- "jest-allure": "^0.1.1",
- allure 2.4.1

jest.config.js
```
module.exports = {
    reporters: ["default", "jest-allure","jest-stare"],
};
```

note: another third party jest reports works without problem.

**Comment by akaguny** [comment]
@kevinoliveira , pls see this #15

**Comment by kevinoliveira** [comment]
i saw the issue you linked and i could not get it to work.

i added globalSetup to my jest.config.js 
```
module.exports = {
    reporters: ["default", "jest-allure","jest-stare"],
    globalSetup: "jest-allure/dist/setup"
};
```
and this is what i get when i run tests
```
ReferenceError: jasmine is not defined
    at registerAllureReporter (/home/USER/PROJECT/node_modules/jest-allure/dist/setup.js:46:5)
    at Object.<anonymous> (/home/USER/PROJECT/node_modules/jest-allure/dist/setup.js:49:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.newLoader [as .js] (/home/USER/PROJECT/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

```

i tried with setupFiles and setupFilesAfterEnv but i got the same results.

**Comment by kevinoliveira** [comment]
this is the same problem addressed in  https://github.com/zaqqaz/jest-allure/issues/8

**Comment by zaqqaz** [comment]
Let's continue in https://github.com/zaqqaz/jest-allure/issues/8 .
