### ISSUE TITLE
How to add Links

### ISSUE THREAD

**Issue by jintoppy** [zaqqaz/jest-allure#17]
In the allure demo report (https://demo.qameta.io/allure/#categories/7de3af51bba611a38d34ef5f5e363d10/1f321e14a38cd67c/), I see that, Links are given. JIRA Links. 

How do I add that with jest-allure?

Thanks

**Comment by zaqqaz** [comment]
For links and all related info you can use `reporter.addParameter(paramName: string, name: string, value: string): this` api. I'm not sure which parameter you should use for jira links, try to check allure doc for that (it's not really related to jest-allure integration).

**Comment by hananmalka** [comment]
@zaqqaz 
Can you give an example?
I created it like this:

```
reporter.addParameter(
      "system-property",
      "allure.link.issue.pattern",
      "https://JIRA_SERVER/{}"
    );
```

But how now can I attach the issue to be a link using the jira server URL?
