### ISSUE TITLE
Image attachment not working reliably

### ISSUE THREAD

**Issue by hroemer** [zaqqaz/jest-allure#2]
Attaching an image is not working reliably. Consider this test code:

```typescript
import { registerAllureReporter } from "jest-allure/dist/setup";

registerAllureReporter();

describe("Reporter", () => {
    test("Attach image", async () => {
        await reporter.description("Attaching an image");

        const img1 = await drawText(`Generated Image`);

        await reporter.startStep("Make a screenshot");
        await reporter.addAttachment("Screenshot", img1, "image/png");
        await reporter.endStep();
    });
});
```
and in order to ease differing between individual test runs, a dynamically generated image using [canvas](https://github.com/Automattic/node-canvas) including the current timestamp:

```typescript
const { createCanvas } = require("canvas");

function drawText(text: string): any {
    const canvas = createCanvas(480, 240);
    const ctx = canvas.getContext("2d");

    ctx.font = "30px Impact";
    const left = 20;
    ctx.fillText(text, left, 80);
    ctx.fillText(`(${new Date().toISOString()})`, left, 120);

    return canvas.toBuffer();
}
```
and this package.json

```json
{
  "scripts": {
    "test": "jest",
    "report": "allure generate --clean"
  },
  "dependencies": {
    "@types/jest": "^23.1.0",
    "allure-commandline": "^2.5.0",
    "canvas": "^2.0.0-alpha.12",
    "jest": "^23.1.0",
    "jest-allure": "^0.1.1"
  },
  "jest": {
    "transform": {
      "^.+\\.tsx?$": "ts-jest"
    },
    "testRegex": "(./.*/.*(\\.test|\\.spec))\\.(ts?|tsx?)$",
    "moduleFileExtensions": [
      "ts",
      "js",
      "json"
    ],
    "reporters": [
      "default",
      "jest-allure"
    ]
  }
}
```

Now run the test repeatedly:

```bash
npm test
```
 and approx. every second run will not contain the image attachment in the report:

```bash
npm run report
```
Am I using this API wrong here or is this a bug?

**Comment by hroemer** [comment]
@zaqqaz thanks for you reply.

Btw, if I remove the `registerAllureReporter` call it won't compile because it can't find the global `reporter` variable then:
```bash
Error:(5, 15) TS2304: Cannot find name 'reporter'.
```
I also had to set the compile flag `allowSyntheticDefaultImports` in order be able to import it in the first place :question:

**Comment by bogomya** [comment]
@hroemer, which version of jest-allure package do you use ?

**Comment by hroemer** [comment]
@bogomya I am using the latest version of jest-allure: 0.1.1.

**Comment by hroemer** [comment]
@bogomya regarding importing the global variable, I can work around it like this:

```typescript
declare const reporter: any;
import "jest-allure/dist/setup";
```
and it even compiles and runs, but it seems wrong to me. 
Am I missing something here? How do you setup a spec file without importing / requiring it first?

**Comment by hroemer** [comment]
I did a couple of test runs today in a larger test suite with importing the globals via:

```typescript
import "jest-allure/dist/setup";
```
Attaching images now seems to be running fine in every run, thus I believe we can close this issue.

**Comment by bogomya** [comment]
@hroemer okay, I will close the issue.
