### ISSUE TITLE
Generate two .xml files

### ISSUE THREAD

**Issue by Strandol** [zaqqaz/jest-allure#3]
Hi. I have the next problem: jest-allure generate two .xml files, one of them has an empty <test-cases>, but second is fulfilled.
In my package.json file i use
`"jest": {
"setupTestFrameworkScriptFile": "./jest.setup.js"
}`

In jest.setup.js i used
const { registerAllureReporter } = require("jest-allure/dist/setup")
registerAllureReporter();

In file ./node-modules/jest-allure/src/setup.ts
I noticed that you are using registerAllureReporter() in the end of code
![image](https://user-images.githubusercontent.com/23364749/43184938-01488334-8ff3-11e8-98cc-135741925998.png). I think it generate .xml second time.

I resolved my issue by the next direction:
In jest.setup.js I just require file ./jest-allure/dist/setup
`require("jest-allure/dist/setup")` and dont use registerAllureReporter(),

I think, you need to correct example with "setupTestFrameworkScriptFile"

**Comment by zaqqaz** [comment]
@Strandol you're right, nice catch! 
I'll update readme soon.

**Comment by stevelibuzz** [comment]
I have the similar problem, thanks for the post. 
And I have another question related to it, how to specify the result folder if using const { registerAllureReporter } = require("jest-allure/dist/setup") in jest.setup.js?

**Comment by zaqqaz** [comment]
Readme updated.

@stevelibuzz basically, you just need to add clean import: 
```
import "jest-allure/dist/setup";
```
