### ISSUE TITLE
help - unable to use example - error importing {Severity}

### ISSUE THREAD

**Issue by andreabisello** [zaqqaz/jest-allure#36]
node version v10.16.3
jest version 24.9.0

installed allure

![image](https://user-images.githubusercontent.com/2149815/68198042-9842e980-ffbb-11e9-9859-5664cc73a341.png)

created alloro.test.js file

![image](https://user-images.githubusercontent.com/2149815/68197847-397d7000-ffbb-11e9-85dd-e44c854a1180.png)

added jest-allure/dist/setup in the jest.config.js

![image](https://user-images.githubusercontent.com/2149815/68197871-48fcb900-ffbb-11e9-97f4-09718407662b.png)

launching test

![image](https://user-images.githubusercontent.com/2149815/68197993-85301980-ffbb-11e9-8ce6-379c4b11d7f4.png)

some help please?

thanks

**Comment by Moshisho** [comment]
@andreabisello try using `const { Severity } = require('jest-allure/dist/Reporter');` instead of using import syntax which requires babel.

**Comment by andreabisello** [comment]
@Moshisho  it works,
thanks.
