### ISSUE TITLE
i would like to "allure generate" something can be attached / shared / locally opened

### ISSUE THREAD

**Issue by andreabisello** [zaqqaz/jest-allure#44]
allure reports are awesome,
but i need to attach to an html page.
even i zip the folder,
the reports cannot be locally opened.
![image](https://user-images.githubusercontent.com/2149815/72065170-e6d37380-32dd-11ea-873e-3bdaf247d172.png)
i would avoid to use the allure serve,
maybe because i would like to share this report with something else, maybe by email.

**Comment by zaqqaz** [comment]
Close, as it's part of the allure functionality and not directly related to the jest-allure. But instead of allure serve you can use any static server eg `python -m SimpleHTTPServer 8000`. AFAIK there are also some plugins available to convert allure reports to doc/pdf formats.
