### ISSUE TITLE
TS error Cannot find name reporter

### ISSUE THREAD

**Issue by kirill-konshin** [zaqqaz/jest-allure#50]
I have a monorepository, and when I am editing test files I see following error in WebStorm:

```
xxx.spec.tsx:21:9 - error TS2304: Cannot find name 'reporter'.
21  reporter.epic('xxx');
```

Funny part is that tests are passing, since Jest use Babel to transpile, which does not verify types.

I've added following to my tsconfig, but it still fails:

```json
{
  "compilerOptions": {
    "typeRoots": [
      "node_modules/@types",
      "node_modules/jest-allure/dist"
    ]
}
```

**Comment by iamolegga** [comment]
Any luck with this?

**Comment by kirill-konshin** [comment]
I just switched to official integration: https://github.com/allure-framework/allure-js, documentation is a bit missing, but things work as expected.

**Comment by iamolegga** [comment]
Ok, thanks 👍

**Comment by tims-j** [comment]
Also running into this same issue. Tried implementing the core allure-js lib but still ran into typescript errors because 'reporter' could not be found on the global scope.

@kirill-konshin do you have any suggestions or could you share how you went about implementing it. As you mentioned the allure docs have a fair bit to be desired.

**Comment by kirill-konshin** [comment]
```js
// jest.config.js
module.exports = {
  // regular stuff
  setupFilesAfterEnv: [require.resolve('./jest.setup.js')]
};
```

```js
// jest.setup.js
const {JasmineAllureReporter} = require('allure-jasmine');
const {Status} = require('allure-js-commons');

const reporter = new JasmineAllureReporter({
    resultsDir: process.env.ALLURE_RESULTS_DIR || './allure-results',
    testMapper: result => {
        if (result.status === Status.SKIPPED) result.fullName = `(WAS SKIPPED) ${result.fullName}`;
        return result;
    }
});

const allure = reporter.getInterface();

global['jasmine'].getEnv().addReporter(reporter);
global['allure'] = allure;
global['reporter'] = reporter;
```

Then you can use `allure` global variable in tests: `allure.step(...)` etc.

**Comment by tims-j** [comment]
@kirill-konshin awesome, thanks for that.

**Comment by Xotabu4** [comment]
You can create 
index.d.ts file in root of your project and put:
```typescript
declare const reporter: {
    description(description: string): this;
    severity(severity: Severity): this;
    epic(epic: string): this;
    feature(feature: string): this;
    story(story: string): this;
    startStep(name: string): this;
    endStep(status?: Status): this;
    addArgument(name: string): this;
    addEnvironment(name: string, value: string): this;
    addAttachment(name: string, buffer: any, type: string): this;
    addLabel(name: string, value: string): this;
    addParameter(paramName: string, name: string, value: string): this;
}
```
into it

**Comment by kirill-konshin** [comment]
@Xotabu4 this would work, but this is not the optimal solution, as every project will have to drag this copy-paste. It has to be resolved at lib level.

**Comment by Xotabu4** [comment]
> @Xotabu4 this would work, but this is not the optimal solution, as every project will have to drag this copy-paste. It has to be resolved at lib level.

Yes, thats just a workaround

**Comment by katiecookson** [comment]
It says right at the bottom of this link: https://www.npmjs.com/package/jest-allure

Warning
jest-allure reporter dynamically configure "setupTestFrameworkScriptFile" option in Jest configuration. If you have your own setupTestFrameworkScriptFile file, you need to manually register allure reporter, for it you need to import jest-allure/dist/setup.

import "jest-allure/dist/setup";

Adding this import worked for me.

**Comment by zaqqaz** [comment]
Just include `node_modules/jest-allure/dist/setup.d.ts` in your tsconfig (which has declaration for global reporter), for example, like: 

```
  "files": [ "node_modules/jest-allure/dist/setup.d.ts" ],
```

**Comment by kirill-konshin** [comment]
When using Yarn 2 in PNP mode there won't be any `node_modules`...
