### ISSUE TITLE
How to set the resultsDir ? 

### ISSUE THREAD

**Issue by WarleyGabriel** [zaqqaz/jest-allure#71]
Hi, is there any way to replace `resultsDir`?

I'm using this configuration on my package.json, and I don't know how to set the resultsDir here:
```
"jest": {
    "reporters": [
      "default"
    ],
    "setupFilesAfterEnv": [
      "jest-allure/dist/setup"
    ]
  },
```

I would like to save the result files in another directory.

**Comment by WarleyGabriel** [comment]
I've found a solution here: https://stackoverflow.com/questions/65125342/javascript-allure-results-for-jest-allure-specify-the-out-directory

Add `"<rootDir>/jest-allure-config.js"` on package.json:
```
"setupFilesAfterEnv": [
      "jest-allure/dist/setup",
      "<rootDir>/jest-allure-config.js"
    ]
```

Create `jest-allure-config.js` file:
```

reporter.allure.setOptions({ targetDir: 'test-report/allure-result' });
```

**Comment by zaqqaz** [comment]
That's correct solution 👍
